import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import NavLinks from "./ui/NavLinks/NavLinks";
import { mainLinks } from "./ui/NavLinks/linksData";
import DarkModeSwitch from "./ui/DarkModeSwitch/DarkModeSwitch";
import Providers from "./Providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl" suppressHydrationWarning className="h-full">
      <body className={`${inter.className} font-sans`}>
        <Providers>
          <header>
            Header section
            <DarkModeSwitch />
          </header>
          <NavLinks links={mainLinks} />
          <main className="flex-grow">{children}</main>
          <footer>Footer section</footer>
        </Providers>
      </body>
    </html>
  );
}
